### ISSUE TITLE
Why map all k8s workload types to `deployment`?

### ISSUE THREAD

**Issue by devonhk** [grafana/agent-modules#29]
All K8s workload labels are mapped to the `deployment` label.

e.g:
https://github.com/grafana/agent-modules/blob/main/modules/kubernetes/relabelings/pod.river#L76
https://github.com/grafana/agent-modules/blob/main/modules/kubernetes/relabelings/pod.river#L89

Was this done for cost saving or performance reasons, to reduce the amount of data that needs to be indexed?
At first I thought this was a bug, but it seems to be intentional.

**Comment by bentonam** [comment]
@devonhk This was done to reduce cardinality of labels specifically for Loki, for metrics there is still a pod label present as well.  The thought behind it is cardinality (uniqueness) can impact performance if a label is not used.  Given that it is highly unlikely a user will actually filter or use a `pod` label in their queries the modules omit it.  There is an argument which can be made that "I need to know the pod name", this is where the `logs.agent.grafana.com/embed-pod: "true"` annotation comes in, it will add the string __pod="grafana-agent-logs-xxxxx"` to the end of the log line, if it is json a new property of `"__pod":` will be added, which allows you to filter on the line using the pod name without it being an actual label.  i.e. 

```
{deployment="DaemonSet/grafana-agent-logs"} |= `__pod="grafana-agent-logs-xxxxx"`}
```

This may change in the future to be structured metadata instead, of altering the log line.  

Does this answer your question?  If the pod name as a label is desired anyway, we can considering adding it so the label is present, but is still excluded by default but could be allowed through the `keep_labels` argument.

**Comment by bentonam** [comment]
@devonhk I am assuming that this answered your question and I'm going to close this issue.

**Comment by devonhk** [comment]
Yes that answered my question. Thanks for the detailed response.
