### ISSUE TITLE
Allow enabling clustering for prometheus scrape configs

### ISSUE THREAD

**Issue by akshaymankar** [grafana/agent-modules#37]
It is still a beta feature, but it would be very helpful to me if the  modules took an argument like `enable_clustering` and passed it to all the `prometheus.scrape` components.

**Comment by bentonam** [comment]
@akshaymankar Is there specific modules that you are referring to?

**Comment by akshaymankar** [comment]
I use the k8s_api module but I guess it would be good to have in all of them?

**Comment by bentonam** [comment]
@akshaymankar I have recently added modules for specific jobs here https://github.com/grafana/agent-modules/tree/main/modules/kubernetes/metrics/jobs that have standard arguments for each scrape, including `clustering`.  Will these work for you?

**Comment by akshaymankar** [comment]
They work for me. Thanks.
